server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: product-warehouse-service
        uri: http://localhost:8083/
        predicates:
        - Path=/v1/items/**
      - id: order-service
        uri: http://localhost:8082/
        predicates:
        - Path=/v1/orders/**

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true